// AUTO-GENERATED from live API (13 May - 11 Jun 2026). Real Vivo data snapshot for canvas prototype.
export interface StoreRow { store:string; country:string; orders:number; units:number; sales:number; abv:number; footfall:number; conversion:number|null; salesPerVisitor:number|null; sensorGap:number; lowVolume:boolean; noFootfall:boolean; convReliable:boolean; }
export const NETWORK = {"netConv": 13.2, "netAbv": 8851, "netSpv": 1200, "window": "13 May - 11 Jun 2026", "relCount": 28, "total": 30};
export const STORES: StoreRow[] = [
  {
    "store": "Shop Zetu",
    "country": "Online",
    "orders": 1295,
    "units": 2277,
    "sales": 8436571,
    "abv": 6515,
    "footfall": 0,
    "conversion": null,
    "salesPerVisitor": null,
    "sensorGap": 0,
    "lowVolume": false,
    "noFootfall": true,
    "convReliable": false
  },
  {
    "store": "Junction",
    "country": "Kenya",
    "orders": 790,
    "units": 1945,
    "sales": 8393899,
    "abv": 10625,
    "footfall": 6104,
    "conversion": 12.9,
    "salesPerVisitor": 1375,
    "sensorGap": 0,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  },
  {
    "store": "Sarit",
    "country": "Kenya",
    "orders": 974,
    "units": 1994,
    "sales": 7926609,
    "abv": 8138,
    "footfall": 5448,
    "conversion": 17.9,
    "salesPerVisitor": 1455,
    "sensorGap": 0,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  },
  {
    "store": "Mama Ngina St",
    "country": "Kenya",
    "orders": 590,
    "units": 1247,
    "sales": 5293274,
    "abv": 8972,
    "footfall": 3553,
    "conversion": 16.6,
    "salesPerVisitor": 1490,
    "sensorGap": 0,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  },
  {
    "store": "Yaya",
    "country": "Kenya",
    "orders": 454,
    "units": 1144,
    "sales": 4856295,
    "abv": 10697,
    "footfall": 3048,
    "conversion": 14.9,
    "salesPerVisitor": 1593,
    "sensorGap": 0,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  },
  {
    "store": "Moi Avenue",
    "country": "Kenya",
    "orders": 629,
    "units": 1214,
    "sales": 4721474,
    "abv": 7506,
    "footfall": 5960,
    "conversion": 10.6,
    "salesPerVisitor": 792,
    "sensorGap": 0,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  },
  {
    "store": "Village Market",
    "country": "Kenya",
    "orders": 491,
    "units": 1079,
    "sales": 4616941,
    "abv": 9403,
    "footfall": 3543,
    "conversion": 13.5,
    "salesPerVisitor": 1303,
    "sensorGap": 1,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  },
  {
    "store": "Kigali Heights",
    "country": "Rwanda",
    "orders": 332,
    "units": 883,
    "sales": 4109790,
    "abv": 12379,
    "footfall": 1821,
    "conversion": 18.2,
    "salesPerVisitor": 2257,
    "sensorGap": 0,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  },
  {
    "store": "Acacia",
    "country": "Uganda",
    "orders": 274,
    "units": 699,
    "sales": 3731985,
    "abv": 13620,
    "footfall": 2194,
    "conversion": 12.5,
    "salesPerVisitor": 1701,
    "sensorGap": 0,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  },
  {
    "store": "Garden City",
    "country": "Kenya",
    "orders": 352,
    "units": 809,
    "sales": 3477852,
    "abv": 9880,
    "footfall": 2722,
    "conversion": 9.6,
    "salesPerVisitor": 1278,
    "sensorGap": 5,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  },
  {
    "store": "Galleria",
    "country": "Kenya",
    "orders": 343,
    "units": 742,
    "sales": 3156100,
    "abv": 9201,
    "footfall": 2472,
    "conversion": 13.9,
    "salesPerVisitor": 1277,
    "sensorGap": 0,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  },
  {
    "store": "City Mall",
    "country": "Kenya",
    "orders": 331,
    "units": 679,
    "sales": 2986547,
    "abv": 9023,
    "footfall": 2078,
    "conversion": 14.4,
    "salesPerVisitor": 1437,
    "sensorGap": 5,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  },
  {
    "store": "TRM",
    "country": "Kenya",
    "orders": 347,
    "units": 675,
    "sales": 2906728,
    "abv": 8377,
    "footfall": 2193,
    "conversion": 15.8,
    "salesPerVisitor": 1325,
    "sensorGap": 0,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  },
  {
    "store": "Nakuru",
    "country": "Kenya",
    "orders": 327,
    "units": 661,
    "sales": 2882426,
    "abv": 8815,
    "footfall": 1613,
    "conversion": 16.9,
    "salesPerVisitor": 1787,
    "sensorGap": 5,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  },
  {
    "store": "Two Rivers",
    "country": "Kenya",
    "orders": 343,
    "units": 649,
    "sales": 2814172,
    "abv": 8205,
    "footfall": 2660,
    "conversion": 12.9,
    "salesPerVisitor": 1058,
    "sensorGap": 0,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  },
  {
    "store": "Imaara",
    "country": "Kenya",
    "orders": 304,
    "units": 696,
    "sales": 2806393,
    "abv": 9232,
    "footfall": 1872,
    "conversion": 16.2,
    "salesPerVisitor": 1499,
    "sensorGap": 0,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  },
  {
    "store": "Capital Centre",
    "country": "Kenya",
    "orders": 318,
    "units": 664,
    "sales": 2721179,
    "abv": 8557,
    "footfall": 2742,
    "conversion": 11.6,
    "salesPerVisitor": 992,
    "sensorGap": 0,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  },
  {
    "store": "Kisumu",
    "country": "Kenya",
    "orders": 301,
    "units": 603,
    "sales": 2559913,
    "abv": 8505,
    "footfall": 2800,
    "conversion": 10.8,
    "salesPerVisitor": 914,
    "sensorGap": 0,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  },
  {
    "store": "Runda",
    "country": "Kenya",
    "orders": 253,
    "units": 583,
    "sales": 2490557,
    "abv": 9844,
    "footfall": 1008,
    "conversion": 20.3,
    "salesPerVisitor": 2471,
    "sensorGap": 3,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  },
  {
    "store": "Hub",
    "country": "Kenya",
    "orders": 294,
    "units": 592,
    "sales": 2454215,
    "abv": 8348,
    "footfall": 2205,
    "conversion": 13.3,
    "salesPerVisitor": 1113,
    "sensorGap": 0,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  },
  {
    "store": "The Oasis Mall",
    "country": "Uganda",
    "orders": 185,
    "units": 483,
    "sales": 2381222,
    "abv": 12871,
    "footfall": 119,
    "conversion": null,
    "salesPerVisitor": null,
    "sensorGap": 26,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": false
  },
  {
    "store": "Eldoret",
    "country": "Kenya",
    "orders": 301,
    "units": 531,
    "sales": 2315588,
    "abv": 7693,
    "footfall": 2405,
    "conversion": 12.5,
    "salesPerVisitor": 963,
    "sensorGap": 0,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  },
  {
    "store": "T- Mall",
    "country": "Kenya",
    "orders": 234,
    "units": 539,
    "sales": 2230512,
    "abv": 9532,
    "footfall": 1173,
    "conversion": 15.7,
    "salesPerVisitor": 1902,
    "sensorGap": 7,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  },
  {
    "store": "MSA Digo Road",
    "country": "Kenya",
    "orders": 231,
    "units": 425,
    "sales": 1836838,
    "abv": 7952,
    "footfall": 1878,
    "conversion": 12.3,
    "salesPerVisitor": 978,
    "sensorGap": 0,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  },
  {
    "store": "Signature Mall",
    "country": "Kenya",
    "orders": 188,
    "units": 393,
    "sales": 1628233,
    "abv": 8661,
    "footfall": 1569,
    "conversion": 12.0,
    "salesPerVisitor": 1038,
    "sensorGap": 0,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  },
  {
    "store": "Kileleshwa",
    "country": "Kenya",
    "orders": 152,
    "units": 367,
    "sales": 1463610,
    "abv": 9629,
    "footfall": 949,
    "conversion": 16.0,
    "salesPerVisitor": 1542,
    "sensorGap": 0,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  },
  {
    "store": "Greenspan",
    "country": "Kenya",
    "orders": 199,
    "units": 376,
    "sales": 1432195,
    "abv": 7197,
    "footfall": 2109,
    "conversion": 9.4,
    "salesPerVisitor": 679,
    "sensorGap": 0,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  },
  {
    "store": "Safari Sarit",
    "country": "Kenya",
    "orders": 138,
    "units": 249,
    "sales": 1258890,
    "abv": 9122,
    "footfall": 2535,
    "conversion": 5.4,
    "salesPerVisitor": 497,
    "sensorGap": 0,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  },
  {
    "store": "Meru",
    "country": "Kenya",
    "orders": 104,
    "units": 198,
    "sales": 815191,
    "abv": 7838,
    "footfall": 1426,
    "conversion": 7.3,
    "salesPerVisitor": 572,
    "sensorGap": 0,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  },
  {
    "store": "Zoya Sarit",
    "country": "Kenya",
    "orders": 141,
    "units": 283,
    "sales": 562547,
    "abv": 3990,
    "footfall": 3632,
    "conversion": 3.9,
    "salesPerVisitor": 155,
    "sensorGap": 0,
    "lowVolume": false,
    "noFootfall": false,
    "convReliable": true
  }
];

export const ACCENT: Record<string,string> = { Kenya:"#1a5c38", Uganda:"#d97706", Rwanda:"#00c853", Online:"#4b7bec" };
export const fmtKES = (n:number) => "KES " + Math.round(n).toLocaleString("en-US");
export const fmtKESk = (n:number) => n>=1_000_000 ? "KES "+(n/1_000_000).toFixed(1)+"M" : "KES "+Math.round(n/1000)+"k";
export const fmtPct = (n:number|null) => n==null ? "—" : n.toFixed(1)+"%";
