// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/rewards": {
    params: {};
  };
  "/shop": {
    params: {};
  };
  "/shop/product/:handle": {
    params: {
      "handle": string;
    };
  };
  "/cart": {
    params: {};
  };
  "/wishlist": {
    params: {};
  };
  "/orders": {
    params: {};
  };
  "/orders/:orderId": {
    params: {
      "orderId": string;
    };
  };
  "/referrals": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/rewards": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/dashboard" | "/rewards" | "/shop" | "/shop/product/:handle" | "/cart" | "/wishlist" | "/orders" | "/orders/:orderId" | "/referrals" | "/profile" | "/admin" | "/admin/rewards";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/_app.tsx": {
    id: "routes/_app";
    page: "/dashboard" | "/rewards" | "/shop" | "/shop/product/:handle" | "/cart" | "/wishlist" | "/orders" | "/orders/:orderId" | "/referrals" | "/profile" | "/admin" | "/admin/rewards";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/rewards.tsx": {
    id: "routes/rewards";
    page: "/rewards";
  };
  "routes/shop.tsx": {
    id: "routes/shop";
    page: "/shop";
  };
  "routes/product.tsx": {
    id: "routes/product";
    page: "/shop/product/:handle";
  };
  "routes/cart.tsx": {
    id: "routes/cart";
    page: "/cart";
  };
  "routes/wishlist.tsx": {
    id: "routes/wishlist";
    page: "/wishlist";
  };
  "routes/orders.tsx": {
    id: "routes/orders";
    page: "/orders";
  };
  "routes/order-detail.tsx": {
    id: "routes/order-detail";
    page: "/orders/:orderId";
  };
  "routes/referrals.tsx": {
    id: "routes/referrals";
    page: "/referrals";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin";
  };
  "routes/admin-rewards.tsx": {
    id: "routes/admin-rewards";
    page: "/admin/rewards";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/_app": typeof import("./app/routes/_app.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/rewards": typeof import("./app/routes/rewards.tsx");
  "routes/shop": typeof import("./app/routes/shop.tsx");
  "routes/product": typeof import("./app/routes/product.tsx");
  "routes/cart": typeof import("./app/routes/cart.tsx");
  "routes/wishlist": typeof import("./app/routes/wishlist.tsx");
  "routes/orders": typeof import("./app/routes/orders.tsx");
  "routes/order-detail": typeof import("./app/routes/order-detail.tsx");
  "routes/referrals": typeof import("./app/routes/referrals.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/admin-rewards": typeof import("./app/routes/admin-rewards.tsx");
};