// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/locations-viz/Heatmap.tsx": () => import("../components/mockups/locations-viz/Heatmap.tsx"),
  "./components/mockups/locations-viz/Quadrant.tsx": () => import("../components/mockups/locations-viz/Quadrant.tsx")
};
